create table jobs (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	status TINYINT UNSIGNED NOT NULL DEFAULT 1,
	priority INT UNSIGNED NOT NULL DEFAULT 1,
	submitter INT UNSIGNED NOT NULL,
	processor INT UNSIGNED NOT NULL,
	command VARCHAR(255) NOT NULL,
	proc_time DECIMAL(16,12) DEFAULT NULL
);
